meta_product_name: "Handyman Near You!"
meta_title: "Handyman Near You! - List of professional Mauritian handymen around the island!"
meta_description: "You can find a handyman in your local area who can help you fix things around your house. And we provide quotation service on the same Web App"
meta_image: "electrician-cover.jpg" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards